### ISSUE TITLE
Duplicate Files in HS

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/iUtahUtilities#14]
I'm seeing the duplicate file issue crop up in HS again:
![image](https://cloud.githubusercontent.com/assets/5023186/20776995/4a659bda-b721-11e6-9c42-9df79c29bfca.png)

**Comment by fryarludwig** [comment]
It looks like this has been taken care of by the production script we have running on our server. The duplicates likely appeared while I was testing the code, since I was running it repeatedly from my local machine. I'll be sure to keep the duplicate file purging enabled when I run tests in the future.
